// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsbW99RJpJH9_lh1uk6Q-xFOJE31FXSI',
    appId: '1:652350155929:web:b4b3be17d1835eb9259c08',
    messagingSenderId: '652350155929',
    projectId: 'moblan-sisa',
    authDomain: 'moblan-sisa.firebaseapp.com',
    storageBucket: 'moblan-sisa.appspot.com',
    measurementId: 'G-Z2KBRRRJWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlqOnO37fk2UvNp80qY6lwwXiXVm0VA6g',
    appId: '1:652350155929:android:ea5f28d8f610904f259c08',
    messagingSenderId: '652350155929',
    projectId: 'moblan-sisa',
    storageBucket: 'moblan-sisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJPxJmYlUKJNYqNej-AAR8vNqYmAxDBEk',
    appId: '1:652350155929:ios:8b744cd2258c9126259c08',
    messagingSenderId: '652350155929',
    projectId: 'moblan-sisa',
    storageBucket: 'moblan-sisa.appspot.com',
    iosBundleId: 'com.example.sisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJPxJmYlUKJNYqNej-AAR8vNqYmAxDBEk',
    appId: '1:652350155929:ios:ee894d1e5e124356259c08',
    messagingSenderId: '652350155929',
    projectId: 'moblan-sisa',
    storageBucket: 'moblan-sisa.appspot.com',
    iosBundleId: 'com.example.sisa.RunnerTests',
  );
}
